apiVersion: apps/v1
kind: Deployment
metadata:
  name: jdoodle-deploy
  labels:
    apps: jdoodle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jdoodle
  template:
    metadata:
      labels:
        app: jdoodle
    spec:
      containers:
        - name: jdoodle
          image: jdoodle
          imagePullPolicy: Never
          ports:
            - containerPort: 80
